### ISSUE TITLE
Building from git master fails after https://github.com/minbrowser/min/commit/545cf5a177e1bde0cbfda467e54f28594b86636e

### ISSUE THREAD

**Issue by glitsj16** [minbrowser/min#946]
Hi, I've been building min for a while now from git master. After https://github.com/minbrowser/min/commit/545cf5a177e1bde0cbfda467e54f28594b86636e I saw the below output:

```
$ npm install
...

$ npm run buildDebian
...
Error while building: Cannot find module 'readerView.js' from '/home/glitsj16/min/js/searchbar/placesPlugin.js'
Error while building: Cannot find module 'readerView.js' from '/home/glitsj16/min/js/navbar/tabBar.js'
Error while building: Cannot find module 'readerView.js' from '/home/glitsj16/min/js/menuRenderer.js'
```

After renaming `readerview.js` to `readerView.js` (note the camelcase pattern) the above errors disappear. Haven't gotten around yet to extensively test the browser, but it seems to be working just fine with that change. More a FYI I guess.
